from src.sorting import sort_by

jobs_list = [
    {
        "job_title": "Marketing",
        "company": "Relief",
        "state": "NY",
        "city": "New York",
        "min_salary": "",
        "max_salary": "",
        "job_desc": "Marketing operations of the company.",
        "industry": "Finance",
        "rating": "4.0",
        "date_posted": "2020-05-08",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "0",
    },
    {
        "job_title": "Registered Nurse",
        "company": "Queens Boulevard Endoscopy Center",
        "state": "NY",
        "city": "Rego Park",
        "min_salary": "",
        "max_salary": "",
        "job_desc": "Full-Time Registered Nurse!",
        "industry": "",
        "rating": "3.0",
        "date_posted": "2020-04-25",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "1",
    },
    {
        "job_title": "Dental Hygienist",
        "company": "Batista Dental",
        "state": "NJ",
        "city": "West New York",
        "min_salary": "",
        "max_salary": "",
        "job_desc": "description",
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-02",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "2",
    },
    {
        "job_title": "Senior Salesforce Developer",
        "company": "National Debt Relief",
        "state": "NY",
        "city": "New York",
        "min_salary": "44587",
        "max_salary": "82162",
        "job_desc": "description",
        "industry": "Finance",
        "rating": "4.0",
        "date_posted": "2020-05-09",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "3",
    },
    {
        "job_title": ("DEPUTY EXECUTIVE DIRECTOR, PROGRAM AND LEGAL ADVOCACY"),
        "company": "National Advocates for Pregnant Women",
        "state": "NY",
        "city": "New York",
        "min_salary": "125410",
        "max_salary": "212901",
        "job_desc": "description",
        "industry": "",
        "rating": "",
        "date_posted": "2020-04-28",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "4",
    },
    {
        "job_title": "Emergency Veterinarian - NYC",
        "company": "Veterinary Emergency Group",
        "state": "NY",
        "city": "New York",
        "min_salary": "94715",
        "max_salary": "103279",
        "job_desc": "description",
        "industry": "Health Care",
        "rating": "4.9",
        "date_posted": "2020-05-05",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "5",
    },
    {
        "job_title": "ABA Therapist",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": "20000",
        "max_salary": "35000",
        "job_desc": "description",
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-07",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Construction Project Manager",
        "company": "The LiRo Group",
        "state": "NY",
        "city": "Brooklyn",
        "min_salary": "54991",
        "max_salary": "143860",
        "job_desc": "description",
        "industry": "Construction, Repair & Maintenance",
        "rating": "3.8",
        "date_posted": "2020-05-10",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "7",
    },
]

sorted_by_min_salary = [
    {
        "job_title": "ABA Therapist",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": "20000",
        "max_salary": "35000",
        "job_desc": "description",
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-07",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Senior Salesforce Developer",
        "company": "National Debt Relief",
        "state": "NY",
        "city": "New York",
        "min_salary": "44587",
        "max_salary": "82162",
        "job_desc": "description",
        "industry": "Finance",
        "rating": "4.0",
        "date_posted": "2020-05-09",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "3",
    },
    {
        "job_title": "Construction Project Manager",
        "company": "The LiRo Group",
        "state": "NY",
        "city": "Brooklyn",
        "min_salary": "54991",
        "max_salary": "143860",
        "job_desc": "description",
        "industry": "Construction, Repair & Maintenance",
        "rating": "3.8",
        "date_posted": "2020-05-10",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "7",
    },
    {
        "job_title": "Emergency Veterinarian - NYC",
        "company": "Veterinary Emergency Group",
        "state": "NY",
        "city": "New York",
        "min_salary": "94715",
        "max_salary": "103279",
        "job_desc": "description",
        "industry": "Health Care",
        "rating": "4.9",
        "date_posted": "2020-05-05",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "5",
    },
    {
        "job_title": "DEPUTY EXECUTIVE DIRECTOR, PROGRAM AND LEGAL ADVOCACY",
        "company": "National Advocates for Pregnant Women",
        "state": "NY",
        "city": "New York",
        "min_salary": "125410",
        "max_salary": "212901",
        "job_desc": "description",
        "industry": "",
        "rating": "",
        "date_posted": "2020-04-28",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "4",
    },
    {
        "job_title": "Marketing",
        "company": "Relief",
        "state": "NY",
        "city": "New York",
        "min_salary": "",
        "max_salary": "",
        "job_desc": "Marketing operations of the company.",
        "industry": "Finance",
        "rating": "4.0",
        "date_posted": "2020-05-08",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "0",
    },
    {
        "job_title": "Registered Nurse",
        "company": "Queens Boulevard Endoscopy Center",
        "state": "NY",
        "city": "Rego Park",
        "min_salary": "",
        "max_salary": "",
        "job_desc": "Full-Time Registered Nurse!",
        "industry": "",
        "rating": "3.0",
        "date_posted": "2020-04-25",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "1",
    },
    {
        "job_title": "Dental Hygienist",
        "company": "Batista Dental",
        "state": "NJ",
        "city": "West New York",
        "min_salary": "",
        "max_salary": "",
        "job_desc": "description",
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-02",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "2",
    },
]

sorted_by_max_salary = [
    {
        "job_title": "DEPUTY EXECUTIVE DIRECTOR, PROGRAM AND LEGAL ADVOCACY",
        "company": "National Advocates for Pregnant Women",
        "state": "NY",
        "city": "New York",
        "min_salary": "125410",
        "max_salary": "212901",
        "job_desc": "description",
        "industry": "",
        "rating": "",
        "date_posted": "2020-04-28",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "4",
    },
    {
        "job_title": "Construction Project Manager",
        "company": "The LiRo Group",
        "state": "NY",
        "city": "Brooklyn",
        "min_salary": "54991",
        "max_salary": "143860",
        "job_desc": "description",
        "industry": "Construction, Repair & Maintenance",
        "rating": "3.8",
        "date_posted": "2020-05-10",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "7",
    },
    {
        "job_title": "Emergency Veterinarian - NYC",
        "company": "Veterinary Emergency Group",
        "state": "NY",
        "city": "New York",
        "min_salary": "94715",
        "max_salary": "103279",
        "job_desc": "description",
        "industry": "Health Care",
        "rating": "4.9",
        "date_posted": "2020-05-05",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "5",
    },
    {
        "job_title": "Senior Salesforce Developer",
        "company": "National Debt Relief",
        "state": "NY",
        "city": "New York",
        "min_salary": "44587",
        "max_salary": "82162",
        "job_desc": "description",
        "industry": "Finance",
        "rating": "4.0",
        "date_posted": "2020-05-09",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "3",
    },
    {
        "job_title": "ABA Therapist",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": "20000",
        "max_salary": "35000",
        "job_desc": "description",
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-07",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Marketing",
        "company": "Relief",
        "state": "NY",
        "city": "New York",
        "min_salary": "",
        "max_salary": "",
        "job_desc": "Marketing operations of the company.",
        "industry": "Finance",
        "rating": "4.0",
        "date_posted": "2020-05-08",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "0",
    },
    {
        "job_title": "Registered Nurse",
        "company": "Queens Boulevard Endoscopy Center",
        "state": "NY",
        "city": "Rego Park",
        "min_salary": "",
        "max_salary": "",
        "job_desc": "Full-Time Registered Nurse!",
        "industry": "",
        "rating": "3.0",
        "date_posted": "2020-04-25",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "1",
    },
    {
        "job_title": "Dental Hygienist",
        "company": "Batista Dental",
        "state": "NJ",
        "city": "West New York",
        "min_salary": "",
        "max_salary": "",
        "job_desc": "description",
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-02",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "2",
    },
]

sorted_by_date_posted = [
    {
        "job_title": "Construction Project Manager",
        "company": "The LiRo Group",
        "state": "NY",
        "city": "Brooklyn",
        "min_salary": "54991",
        "max_salary": "143860",
        "job_desc": "description",
        "industry": "Construction, Repair & Maintenance",
        "rating": "3.8",
        "date_posted": "2020-05-10",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "7",
    },
    {
        "job_title": "Senior Salesforce Developer",
        "company": "National Debt Relief",
        "state": "NY",
        "city": "New York",
        "min_salary": "44587",
        "max_salary": "82162",
        "job_desc": "description",
        "industry": "Finance",
        "rating": "4.0",
        "date_posted": "2020-05-09",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "3",
    },
    {
        "job_title": "Marketing",
        "company": "Relief",
        "state": "NY",
        "city": "New York",
        "min_salary": "",
        "max_salary": "",
        "job_desc": "Marketing operations of the company.",
        "industry": "Finance",
        "rating": "4.0",
        "date_posted": "2020-05-08",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "0",
    },
    {
        "job_title": "ABA Therapist",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": "20000",
        "max_salary": "35000",
        "job_desc": "description",
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-07",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Emergency Veterinarian - NYC",
        "company": "Veterinary Emergency Group",
        "state": "NY",
        "city": "New York",
        "min_salary": "94715",
        "max_salary": "103279",
        "job_desc": "description",
        "industry": "Health Care",
        "rating": "4.9",
        "date_posted": "2020-05-05",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "5",
    },
    {
        "job_title": "Dental Hygienist",
        "company": "Batista Dental",
        "state": "NJ",
        "city": "West New York",
        "min_salary": "",
        "max_salary": "",
        "job_desc": "description",
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-02",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "2",
    },
    {
        "job_title": "DEPUTY EXECUTIVE DIRECTOR, PROGRAM AND LEGAL ADVOCACY",
        "company": "National Advocates for Pregnant Women",
        "state": "NY",
        "city": "New York",
        "min_salary": "125410",
        "max_salary": "212901",
        "job_desc": "description",
        "industry": "",
        "rating": "",
        "date_posted": "2020-04-28",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "4",
    },
    {
        "job_title": "Registered Nurse",
        "company": "Queens Boulevard Endoscopy Center",
        "state": "NY",
        "city": "Rego Park",
        "min_salary": "",
        "max_salary": "",
        "job_desc": "Full-Time Registered Nurse!",
        "industry": "",
        "rating": "3.0",
        "date_posted": "2020-04-25",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "1",
    },
]


def test_sort_by_criteria():
    sort_by(jobs_list, "min_salary")
    assert jobs_list == sorted_by_min_salary

    sort_by(jobs_list, "max_salary")
    assert jobs_list == sorted_by_max_salary

    sort_by(jobs_list, "date_posted")
    assert jobs_list == sorted_by_date_posted
